export const apps = [
  {
    id: 1,
    title: "CraveCanvas",
    desc: "This curated prompt generates high-quality impactful food images, ready to be used...",
    img: "https://assets.rentprompts.com/DALLE_IMAGES_zIklD21NZvJZyFZQACme_resized_1730931466705_1000x1000.webp", // replace with real image
    likes: 38,
    rating: 5.0,
    featured: true,
    tags: ["IMAGE", "FLUX-SCHNELL"],
    price: 2,
  },
  {
    id: 2,
    title: "Hyperrealistic Astrophotography",
    desc: "Capture the stunning beauty of the night sky with Hyper-Realistic Astrophotography...",
    img: "https://assets.rentprompts.com/1725574222894n111111111111111111111111.jpg",
    likes: 37,
    rating: 5.0,
    featured: false,
    tags: ["IMAGE", "FLUX-SCHNELL"],
    price: 1,
  },
  {
    id: 3,
    title: "Valentine's Day Week Cards",
    desc: "Create stunning anime-style Valentine's Day cards with just a few words!",
    img: " https://assets.rentprompts.com/output%20(14).jpg ",
    likes: 36,
    rating: 5.0,
    featured: true,
    tags: ["IMAGE", "FLUX-SCHNELL"],
    price: 1,
  },
  {
    id: 4,
    title: "Mandala Intricate Designs",
    desc: "Mesmerizing patterns symbolizing harmony, balance, and beauty.",
    img: "https://assets.rentprompts.com/Collages_NivIZnwxD17wmDAezFDq_resized_1734064899129_1000x1000.webp",
    likes: 35,
    rating: 4.7,
    featured: true,
    tags: ["IMAGE", "FLUX-SCHNELL"],
    price: 1,
  },
  {
    id: 5,
    title: "3D Scenic AI Art Creator",
    desc: "Explore magical worlds inside everyday objects with this AI-powered art generator. This app transfor...",
    img: "https://assets.rentprompts.com/my-image-1754394489662.png",
    likes: 30,
    rating: 6.5,
    featured: true,
    tags: ["IMAGE", "FLUX-SCHNELL"],
    price: 20.79,
  },
  {
    id: 6,
    title: "AI Bed Design Generator",
    desc: "Turn bedtime into a delicious dream with our Cozy Food Fantasy Bed Collection—beds designed to look ...",
    img: "https://assets.rentprompts.com/prompt-image-1754686762515-2.jpg",
    likes: 45,
    rating: 4.9,
    featured: true,
    tags: ["IMAGE", "FLUX-SCHNELL"],
    price: 20.79,
  },
  {
    id: 7,
    title: " 3D Paint-to-Character Transformation AI Video Generator",
    desc: "Create mesmerizing hyper-realistic videos where a droplet of paint morphs into a detailed 3D charact...",
    img: "	https://assets.rentprompts.com/ezgif.com-video-to-webp-converter-1.webp",
    likes: 55,
    rating: 5.7,
    featured: true,
    tags: ["IMAGE", "FLUX-SCHNELL"],
    price: 10.79,
  },
];

// LatestProducts Array
export const products = [
  {
    id: 1,
    title: "Wheels In Motion: Transport Pack",
    desc: "Ride into Learning with Land Transport Flashcards and Prompts.",
    img: "	https://assets.rentprompts.com/car.jpg",
    likes: 32,
    rating: 5.0,
    price: 5,
    type: "ASSET",
    featured: true,
  },
  {
    id: 2,
    title: "Sail & Learn: Water Transport",
    desc: "Set sail on a fun learning adventure with water transport prompts.",
    img: "https://assets.rentprompts.com/boat.jpg",
    likes: 31,
    rating: 5.0,
    price: 5,
    type: "ASSET",
    featured: false,
  },

  {
    id: 4,
    title: "Sky Explorers: Air Transport Flashcards ✈️",
    desc: "Soar into Learning with Air Transport Flashcards! ✈️🚁🚀",
    img: "https://assets.rentprompts.com/aeroplane.jpg",
    likes: 29,
    rating: 5.0,
    price: 5,
    type: "ASSET",
    featured: false,
  },
  {
    id: 5,
    title: "Premium AI Art Prompts – Unlock Stunning Visuals Instantly",
    desc: "Premium AI Art Prompts – Unlock Stunning Visuals Instantly.",
    img: "https://assets.rentprompts.com/2-2.png",
    likes: 29,
    rating: 5.0,
    price: 5,
    type: "ASSET",
    featured: false,
  },
  {
    id: 3,
    title: `Festiva AI – Sleek and sophisticated, combining "Festival" + "AI."`,
    desc: "Designing festival posters has never been easier! Festiva AI is an advanced AI-powered tool that let....",
    img: "https://assets.rentprompts.com/Maroon%20and%20Yellow%20Traditional%20Illustrated%20Navratri%20Greeting%20Instagram%20Post.png",
    likes: 32,
    rating: 5.0,
    price: 10,
    type: "ASSET",
    featured: true,
  },
  {
    id: 6,
    title: "ChromaCards: Explore Colors",
    desc: "Explore a world of colors with fun flashcards and prompts.",
    img: "https://assets.rentprompts.com/black.jpg",
    likes: 29,
    rating: 5.0,
    price: 5,
    type: "ASSET",
    featured: false,
  },
];

// testimonials.
export const testimonials = [
  {
    name: "Alice Johnson",
    role: "Digital Artist",
    quote:
      "With Rentprompts, I created my own custom AI art generator and sold it to thousands of creators who love it!",
  },
  {
    name: "Mark Stevens",
    role: "Entrepreneur",
    quote:
      "I built a video marketing app in just a few weeks using Rentprompts. It completely revolutionized my workflow!",
  },
  {
    name: "Sophia Lee",
    role: "Content Creator",
    quote:
      "Rentprompts made it easy to launch my AI-powered content tools and grow my audience fast!",
  },
];

export const stats = [
  { label: "Community Members", value: "25,000+" },
  { label: "Clients", value: "1,200+" },
  { label: "AI Models Integrated", value: "350+" },
];
